--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  NagiosQL
--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  (c) 2005-2023 by Martin Willisegger
--
--  Project   : NagiosQL
--  Component : Update from NagiosQL 3.5.0 to NagiosQL 4.0.0
--  Website   : https://sourceforge.net/projects/nagiosql/
--  Version   : 4.0.0
--  GIT Repo  : https://gitlab.com/wizonet/NagiosQL
--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  Modify existing tbl_settings (there are no database structure changes in this version)
--
UPDATE `tbl_settings` SET `value` = '4.0.0' WHERE `tbl_settings`.`category` = 'db' AND `tbl_settings`.`name` = 'version' LIMIT 1;
