--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  Gohan ZQL
--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  (c) 2005-2023 by Martin Willisegger
--  (c) 2026 by Esteban Monge - Sempai Space
--
--  Project   : Gohan ZQL (fork of NagiosQL)
--  Component : Update from NagiosQL 3.4.1 to NagiosQL 3.5.0
--  Website   : https://github.com/EstebanMonge/gohanzql
--  Version   : 4.0.0
--  GIT Repo  : https://github.com/EstebanMonge/gohanzql
--
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
--
--  Modify existing tbl_settings
--
UPDATE `tbl_settings` SET `value` = '3.5.0' WHERE `tbl_settings`.`name` = 'version' LIMIT 1;
INSERT INTO `tbl_settings` (`id`, `category`, `name`, `value`) VALUES (NULL, 'install', 'hash', SHA2(UUID(),256));
